### ISSUE TITLE
Compile Fatal Error

### ISSUE THREAD

**Issue by FraEgg** [Nikesh001/android_device_xiaomi_santoni#7]
Hi,

i have some fatal error at the last commits device-tree and kernel-tree (santoni_defconfig) to build my rr rom. i have revert some to fix this. Do you have the same issue ?

Cu Frank

**Comment by mayankbali** [comment]
There is no error coming at such please specify your error

Team Ghost

**Comment by Nikesh001** [comment]
U might have faced neverallow rmt_storage sepolicy error

**Comment by FraEgg** [comment]
I have the same problem. the kernel tree stop at 7% with fatal error "qpnp_smbcharger". Revert the last changes in santoni_defconfig and the kernel issue is fixed.

**Comment by Nikesh001** [comment]
Yeah that too i have faced. Revert will solve issue
