### ISSUE TITLE
Fingerprint not work correctly

### ISSUE THREAD

**Issue by FraEgg** [Nikesh001/android_device_xiaomi_santoni#8]
i have a issue with RR (your device and kernel) with the fingerprint sensor.

1. first boot, activate fingerprint, work
2. after deactivate, and reactivate, dont work :(

Do you have a idea?

Very thanks for your great work.

Cu Frank
![nd5uyhu](https://user-images.githubusercontent.com/27672222/33232865-c4ef6b76-d20d-11e7-985f-1d58968be82b.png)

**Comment by Nikesh001** [comment]
get dmesg bro
